version: 2
updates:

  # Maintain dependencies for Python backend
  # - package-ecosystem: "pip"
  #   directory: "/"
  #   schedule:
  #     interval: "monthly"

  # Maintain dependencies for Node.js backend
  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "monthly"

  # Maintain dependencies for React frontend
  - package-ecosystem: "npm"
    directory: "/front-end"
    schedule:
      interval: "monthly"
